config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get '/auth/github/callback' => 'sessions#create'

  resources :users do
    resources :playlists
  end

  get '/signup', to: 'users#new'
  delete '/users/:id', to: 'users#destroy'

  match 'playlists/by_category' => 'playlists#by_category', :via => :get
  resources :playlists
  delete '/playlists/:id', to: 'playlists#destroy'

  resources :songs

  resources :categories do
    resources :playlists, only: [:new]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates_presence_of :name
    has_many :playlists
    has_many :users, through: :playlists
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    validates :name, :category_name, presence: true
    has_many :playlist_songs
    has_many :songs, through: :playlist_songs
    belongs_to :category
    belongs_to :user
    accepts_nested_attributes_for :songs

    def category_name=(name)
        self.category = Category.find_or_create_by(name: name)
    end
    
    def category_name
        self.category ? self.category.name : nil
    end

    def self.by_category
        self.includes(:category).order('categories.name')
    end

end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
    belongs_to :playlist
    belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
    validates :title, :artist, presence: true
    has_many :playlist_songs
    has_many :playlists, through: :playlist_songs

    def song_by
        self.title + " - " + self.artist
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, :password, presence: true
    validates_uniqueness_of :username
    has_many :playlists
    has_many :categories, through: :playlists
    accepts_nested_attributes_for :playlists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private
    
    def current_user
        @current_user ||= User.find_by(:id => session[:id]) if session[:id]
    end

    def logged_in?
        !!current_user
    end

    def playlist_owner?
        (logged_in?) && (current_user == Playlist.find_by_id(params[:id]).user)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def show
        @category = Category.find_by_id(params[:id])
    end

    def index
        @categories = Category.all
    end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    before_action :redirect_if_not_owner, only: [:edit, :update]

    def new
        redirect_to login_path if !logged_in?
        @playlist = Playlist.new
        @song = @playlist.songs.build
    end

    def create
        @playlist = Playlist.new(playlist_params)
        @playlist.user_id = current_user.id
        if @playlist.save
            redirect_to @playlist
        else
            render :new
        end
    end

    def index
        if params[:user_id]
            @playlists = User.find(params[:user_id]).playlists
        else
            @playlists = Playlist.all
        end
    end

    def by_category
        @playlists = Playlist.by_category
    end

    def show
        @playlist = Playlist.find_by_id(params[:id])
        render :'/page_not_found' if @playlist.nil?
    end

    def edit
        @playlist = Playlist.find_by_id(params[:id])
    end

    def update
        @playlist = Playlist.find_by_id(params[:id])
        @playlist.update(playlist_params)    
        @playlist.save ? (redirect_to @playlist) : (render :edit)

    end

    def destroy
        @playlist = Playlist.find_by_id(params[:id])
        @playlist.destroy
        flash[:notice] = "Playlist deleted."
        redirect_to "/"
    end

    private

    def redirect_if_not_owner
        redirect_to root_path if !playlist_owner?
    end

    def playlist_params
        params.require(:playlist).permit(:name, :category_name, :song_ids => [])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end

    def create
        if auth_hash = request.env["omniauth.auth"]
           omniauth_login
        else
            regular_login
        end
    end

    def destroy
        session.delete :id
        redirect_to '/'
    end

    private
 
  def auth
    request.env['omniauth.auth']
  end

  def omniauth_login
    oauth_nickname = request.env["omniauth.auth"]["info"]["nickname"]
    if @user = User.find_by(:username => oauth_nickname)
        session[:id] = @user.id
        redirect_to '/'
    else
        @user = User.new(:username => oauth_nickname, :password => SecureRandom.hex)
        if @user.save
            session[:id] = @user.id
            redirect_to '/'
        else
            raise @user.errors.full_messages.inspect
        end
    end
  end

  def regular_login
    @user = User.find_by(username: params[:username]) if params[:username]
    if @user && @user.authenticate(params[:password])
        session[:id] = @user.id
        redirect_to '/'
    else
        flash[:alert] = "Incorrect Password."
        render :new
    end
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    def new
        @song = Song.new
    end

    def create
        @song = Song.new(song_params)
        if @song.save
            redirect_to @song
        else
            render :new
        end
    end

    def index
        @songs = Song.all
    end

    def show
        @song = Song.find_by_id(params[:id])
        render :'/page_not_found' if @song.nil?
    end

    private

    def song_params
        params.require(:song).permit(:title, :artist)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        @playlist = @user.playlists.build
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def show
        @user = User.find_by_id(params[:id])
        render :'/page_not_found' if @user.nil?
    end

    def edit
        @user = User.find_by_id(params[:id])
        render :'/page_not_found' if current_user != User.find_by_id(params[:id])
    end

    def update
        @user = User.find_by_id(params[:id])
        @user.update(user_params)
        @user.save ? (redirect_to @user) : (render :edit)
    end

    def destroy
        @user = User.find_by_id(params[:id])
        @user.destroy
        flash[:notice] = "User deleted."
        redirect_to "/"
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :playlists_attributes => [:name, :category])
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def home
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @current_user ||= User.find_by(:id => session[:id]) if session[:id]
    end

    def logged_in?
        !!current_user
    end

    def correct_user?
        (logged_in?) && (current_user == User.find_by_id(params[:id]))
    end

    def playlist_owner?
        (logged_in?) && (current_user == Playlist.find_by_id(params[:id]).user)
    end

end

app/views/categories/index.html.erb
<h3>All Playlist Categories:</h3><br><br>

<% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
<% end %>

app/views/categories/show.html.erb
<h3><%= @category.name %></h3><br>

<%= link_to "Create a new #{@category.name} playlist", new_category_playlist_path(@category) %><br><br>

<h4>This category currently has <%= pluralize(@category.playlists.count, "playlist") %>:</h4>

<% @category.playlists.each do |playlist| %>
    <li><%= link_to playlist.name, playlist_path(playlist) %> by <%= link_to playlist.user.username, user_path(playlist.user) %></li>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <h3>
          <%= pluralize(object.errors.count, "error") %>
          prohibited this from being saved:
        </h3>
        <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
    </div><br>
<% end %>

app/views/layouts/_navbar.html.erb
<% if logged_in? %>
    <%= link_to "View Playlist Categories", categories_path %>
    <%= "•" %>
    <%= link_to "View All Playlists", playlists_path %>
    <%= "•" %>
    <%= link_to "View All Songs", songs_path %>
    <%= "•" %>
    <%= link_to "Create a Playlist", new_playlist_path %>
    <%= "•" %>
    <%= link_to "Create a Song", new_song_path %>
    <%= "•" %>
    <%= link_to "My Profile", user_path(current_user) %><br><br>
    <%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
        <input type=submit value='Logout'>
    <% end %><br>
<% else %>
    <%= link_to "Log In", login_path %>
    <%= "•" %>
    <%= link_to "Sign Up", signup_path %>
    <%= "•" %>
    <%= link_to "Log in with Github", "/auth/github" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playlist Maker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>

    <%= yield %>
  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_for @playlist do |f| %>

    <%= render partial: "layouts/errors", locals: {object: @playlist} %>

    <%= f.label :name %>
    <%= f.text_field :name %><br><br>

    <% if params[:category_id] %>
      <%= f.hidden_field :category_id, value: Category.find_by_id(params[:category_id]).id %>
      <%= f.hidden_field :category_name, value: Category.find_by_id(params[:category_id]).name %>
    <% else %>
      <%= f.label :category %>
      <%= f.text_field :category_name, list: "categories_autocomplete" %>
      <datalist id="categories_autocomplete">
      <% Category.all.each do |category| %>
          <option value="<%= category.name %>">
      <% end %>
      </datalist><br><br>
    <% end %>

    <h4>Add Songs to Your Playlist:</h4>
    <%= f.collection_check_boxes :song_ids, Song.all, :id, :song_by do |s| %><br><br>
      <%= s.label {s.check_box + s.text} %>
    <% end %><br><br>
    <%= f.submit %><br>
<% end %>

app/views/playlists/by_category.html.erb
<h3>Playlists by Category: </h3><br>

<% @playlists.each do |p| %>
    <li><%= link_to p.name, playlist_path(p) %> - <%= p.category.name %></li><br>
<% end %>

app/views/playlists/edit.html.erb
<h3>Edit <%= @playlist.name %></h3><br><br>

<%= render partial: "form" %>

app/views/playlists/index.html.erb
<h3>All Playlists</h3>
<% @playlists.each do |playlist| %>
    <li><%= link_to playlist.name, playlist_path(playlist) %> by <%= link_to playlist.user.username, user_path(playlist.user) %></li><br><br>
<% end %>

<%= link_to "View Playlists by Category", playlists_by_category_path %>

app/views/playlists/new.html.erb
<h3>Create a Playlist</h3><br><br>

<%= render partial: "form" %>

app/views/playlists/show.html.erb
<h2><%= @playlist.name %></h2>
<h4>Created by <%= link_to @playlist.user.username, user_path(@playlist.user) %></h4>
<p><b>Category: </b><%= link_to @playlist.category.name, category_path(@playlist.category) %><p><br>

<% @playlist.songs.each do |song| %>
    <li><b><%= song.title %></b> by <b><%= song.artist %></b></li>
<% end %><br><br>

<% if playlist_owner? %>
    <%= link_to "Edit Playlist", edit_playlist_path(@playlist) %><br><br> 
    <%= link_to "Browse Songs", songs_path %><br><br><br>
    <%= form_tag playlist_path(@playlist.id), method: "delete" do %>
        <%= submit_tag "Delete #{@playlist.name}" %>
  <% end %>
<% end %>

app/views/songs/index.html.erb
<h3>All Songs: </h3><br>

<% @songs.each do |song| %>
    <li><%= link_to song.title, song_path(song) %> by <%= song.artist %></li>
<% end %>

app/views/songs/new.html.erb
<h3>Create a Song</h3><br><br>

<%= form_for @song do |f| %>

    <%= render partial: "layouts/errors", locals: {object: @song} %>

    <%= f.label :title %>
    <%= f.text_field :title %><br><br>
    <%= f.label :artist %>
    <%= f.text_field :artist %><br><br>
    <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h3><%= @song.title %></h3>
<h4>by <%= @song.artist %></h4><br>

<%= link_to "View all Songs", songs_path %>

app/views/users/edit.html.erb
<h3>Edit User</h3><br><br>
<%= form_for @user do |f| %>

    <%= render partial: "layouts/errors", locals: {object: @user} %>

    <%= f.label :username %>
    <%= f.text_field :username %><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br><br>

    <%= f.submit "Save Changes" %>
<% end %>

app/views/users/new.html.erb
<h3>Sign Up</h3><br><br>
<%= form_for @user do |f| %>

    <%= render partial: "layouts/errors", locals: {object: @user} %>

    <%= f.label :username %>
    <%= f.text_field :username %><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br><br>

    <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h3><%= @user.username %>'s Profile</h3><br>

<%= link_to "View #{@user.username}'s Playlists", user_playlists_path(@user) %><br><br>

<% if correct_user? %>
  <%= link_to "Edit Profile", edit_user_path(@user) %><br><br>
  <%= form_tag user_path(@user.id), method: "delete" do %>
    <%= submit_tag "Delete #{@user.username}" %>
  <% end %>
<% end %>

app/views/welcome/home.html.erb
<h1>Welcome to Playlist Maker!</h1><br>